#Experiment-13
##Name-Divisha Ingavale
##PRN-25070123043
##Batch:A-2
#Data Binning & Data Formatting using Python

In [1]:
import pandas as pd
import numpy as np
data={
    'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price':[55000,20000,3000,2000,8000,45000],
    'Units_sold':[25,60,35,80,50,15]
}
df=pd.DataFrame(data)
print(df)

      Product  Price  Units_sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet   3000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [2]:
#Data Binning
bins1=[0,10000,30000,60000]
labels1=['Low','Medium','High']
df['Price_Category']=pd.cut(df['Price'],bins=bins1,labels=labels1)
print(df)

      Product  Price  Units_sold Price_Category
0      Laptop  55000          25           High
1      Mobile  20000          60         Medium
2      Tablet   3000          35            Low
3  Headphones   2000          80            Low
4  Smartwatch   8000          50            Low
5      Camera  45000          15           High

In [3]:
#Binning Units Sold
bins2=[0,30,60,100]
labels2=['Less Sold','Moderately Sold','Highly Sold']
df['Units_Category']=pd.cut(df['Units_sold'],bins=bins2,labels=labels2)
print(df)

      Product  Price  Units_sold Price_Category   Units_Category
0      Laptop  55000          25           High        Less Sold
1      Mobile  20000          60         Medium  Moderately Sold
2      Tablet   3000          35            Low  Moderately Sold
3  Headphones   2000          80            Low      Highly Sold
4  Smartwatch   8000          50            Low  Moderately Sold
5      Camera  45000          15           High        Less Sold

In [4]:
#Data Formatting
#Convert Data Type
print(df.dtypes)
df['Units Sold']=df['Units_sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_sold           int64
Price_Category    category
Units_Category    category
dtype: object
Product             object
Price                int64
Units_sold           int64
Price_Category    category
Units_Category    category
Units Sold         float64
dtype: object

In [5]:
#Convert Text to Uppercaste
df['Product']=df['Product'].str.upper()
print(df)

      Product  Price  Units_sold Price_Category   Units_Category  Units Sold
0      LAPTOP  55000          25           High        Less Sold        25.0
1      MOBILE  20000          60         Medium  Moderately Sold        60.0
2      TABLET   3000          35            Low  Moderately Sold        35.0
3  HEADPHONES   2000          80            Low      Highly Sold        80.0
4  SMARTWATCH   8000          50            Low  Moderately Sold        50.0
5      CAMERA  45000          15           High        Less Sold        15.0

In [6]:
#Rounding Values
df['Price']=df['Price'].round(2)
print(df)

      Product  Price  Units_sold Price_Category   Units_Category  Units Sold
0      LAPTOP  55000          25           High        Less Sold        25.0
1      MOBILE  20000          60         Medium  Moderately Sold        60.0
2      TABLET   3000          35            Low  Moderately Sold        35.0
3  HEADPHONES   2000          80            Low      Highly Sold        80.0
4  SMARTWATCH   8000          50            Low  Moderately Sold        50.0
5      CAMERA  45000          15           High        Less Sold        15.0

In [7]:
#Additional Operations
#Sort Data
sorted_df=df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_sold Price_Category   Units_Category  Units Sold
3  HEADPHONES   2000          80            Low      Highly Sold        80.0
2      TABLET   3000          35            Low  Moderately Sold        35.0
4  SMARTWATCH   8000          50            Low  Moderately Sold        50.0
1      MOBILE  20000          60         Medium  Moderately Sold        60.0
5      CAMERA  45000          15           High        Less Sold        15.0
0      LAPTOP  55000          25           High        Less Sold        25.0

In [8]:
#Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [9]:
#Dataset:Food Delivery Orders
data={'order_ID':['1','2','3','4','5','6','7','8'],
      'order_value':[250,450,120,600,300,150,500,220],
      'delivery_time':[30,45,25,60,35,20,50,28],
      'distance_km':[5,8,3,10,6,2,9,4]}

df=pd.DataFrame(data)
print(df)

  order_ID  order_value  delivery_time  distance_km
0        1          250             30            5
1        2          450             45            8
2        3          120             25            3
3        4          600             60           10
4        5          300             35            6
5        6          150             20            2
6        7          500             50            9
7        8          220             28            4

In [10]:
#Binning Order Value
bins=[0,200,400,700]
labels=['less orders','moderate orders','high orders']
df['order_category']=pd.cut(df['order_value'],bins=bins,labels=labels)
print(df)

  order_ID  order_value  delivery_time  distance_km   order_category
0        1          250             30            5  moderate orders
1        2          450             45            8      high orders
2        3          120             25            3      less orders
3        4          600             60           10      high orders
4        5          300             35            6  moderate orders
5        6          150             20            2      less orders
6        7          500             50            9      high orders
7        8          220             28            4  moderate orders

In [11]:
#Binning Delivery Time
bins2=[0,30,45,70]
labels2=['less time','moderate time','high time']
df['delivery_category']=pd.cut(df['delivery_time'],bins=bins2,labels=labels2)
print(df)

  order_ID  order_value  delivery_time  distance_km   order_category  \
0        1          250             30            5  moderate orders
1        2          450             45            8      high orders
2        3          120             25            3      less orders
3        4          600             60           10      high orders
4        5          300             35            6  moderate orders
5        6          150             20            2      less orders
6        7          500             50            9      high orders
7        8          220             28            4  moderate orders

  delivery_category
0         less time
1     moderate time
2         less time
3         high time
4     moderate time
5         less time
6         high time
7         less time

In [12]:
#Data Formatting Examples
#convert distance to float
df['distance_km']=df['distance_km'].astype(float)
print(df)

  order_ID  order_value  delivery_time  distance_km   order_category  \
0        1          250             30          5.0  moderate orders
1        2          450             45          8.0      high orders
2        3          120             25          3.0      less orders
3        4          600             60         10.0      high orders
4        5          300             35          6.0  moderate orders
5        6          150             20          2.0      less orders
6        7          500             50          9.0      high orders
7        8          220             28          4.0  moderate orders

  delivery_category
0         less time
1     moderate time
2         less time
3         high time
4     moderate time
5         less time
6         high time
7         less time

In [13]:
#Convert Order_ID to Uppercase
df['order_ID']=df['order_ID'].str.upper()
print(df)

  order_ID  order_value  delivery_time  distance_km   order_category  \
0        1          250             30          5.0  moderate orders
1        2          450             45          8.0      high orders
2        3          120             25          3.0      less orders
3        4          600             60         10.0      high orders
4        5          300             35          6.0  moderate orders
5        6          150             20          2.0      less orders
6        7          500             50          9.0      high orders
7        8          220             28          4.0  moderate orders

  delivery_category
0         less time
1     moderate time
2         less time
3         high time
4     moderate time
5         less time
6         high time
7         less time

In [14]:
#check data types
print(df.dtypes)

order_ID               object
order_value             int64
delivery_time           int64
distance_km           float64
order_category       category
delivery_category    category
dtype: object

In [15]:
#Unique Categories
print(df['order_category'].unique())
df

['moderate orders', 'high orders', 'less orders']
Categories (3, object): ['less orders' < 'moderate orders' < 'high orders']

,order_ID,order_value,delivery_time,distance_km,order_category,delivery_category
0,1,250,30,5.0,moderate orders,less time
1,2,450,45,8.0,high orders,moderate time
2,3,120,25,3.0,less orders,less time
3,4,600,60,10.0,high orders,high time
4,5,300,35,6.0,moderate orders,moderate time
5,6,150,20,2.0,less orders,less time
6,7,500,50,9.0,high orders,high time
7,8,220,28,4.0,moderate orders,less time

In [16]:
#count of categories
print(df['order_category'].value_counts())
df

order_category
moderate orders    3
high orders        3
less orders        2
Name: count, dtype: int64

,order_ID,order_value,delivery_time,distance_km,order_category,delivery_category
0,1,250,30,5.0,moderate orders,less time
1,2,450,45,8.0,high orders,moderate time
2,3,120,25,3.0,less orders,less time
3,4,600,60,10.0,high orders,high time
4,5,300,35,6.0,moderate orders,moderate time
5,6,150,20,2.0,less orders,less time
6,7,500,50,9.0,high orders,high time
7,8,220,28,4.0,moderate orders,less time

In [17]:
#sorting
print(df.sort_values(by='order_value'))

  order_ID  order_value  delivery_time  distance_km   order_category  \
2        3          120             25          3.0      less orders
5        6          150             20          2.0      less orders
7        8          220             28          4.0  moderate orders
0        1          250             30          5.0  moderate orders
4        5          300             35          6.0  moderate orders
1        2          450             45          8.0      high orders
6        7          500             50          9.0      high orders
3        4          600             60         10.0      high orders

  delivery_category
2         less time
5         less time
7         less time
0         less time
4     moderate time
1     moderate time
6         high time
3         high time